/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BO.CitaBO;
import BO.DoctorBO;
import BO.PacienteBO;
import Conexion.ConexionBD;
import DTO.CitaNuevoDTO;
import DTO.PacienteNuevoDTO;
import Entidades.Cita;
import Entidades.Doctor;
import Exception.NegocioException;
import java.sql.Date;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Maryr
 */
public class FrmAgendarCitaPaciente extends javax.swing.JFrame {

    private String identificador;
    private CitaBO citaBO;
    private PacienteBO pacienteBO;
    private DoctorBO doctorBO;
    /**
     * Creates new form FrmInicioPaciente
     */
    public FrmAgendarCitaPaciente(String identificador) {
        ConexionBD conexion = new ConexionBD();
        this.citaBO = new CitaBO(conexion);
        this.pacienteBO = new PacienteBO(conexion);
        this.doctorBO = new DoctorBO(conexion);
        this.identificador = identificador;
        initComponents();
        cargarEspecialidades();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BtnCitasSide = new javax.swing.JButton();
        BtnInfoSide = new javax.swing.JButton();
        BtnHistorialSide = new javax.swing.JButton();
        BtnCitaEmSide = new javax.swing.JButton();
        BtnInicio = new javax.swing.JButton();
        BtnCancel = new javax.swing.JPanel();
        LblEspecialidad = new javax.swing.JLabel();
        LblDoctor = new javax.swing.JLabel();
        LblFecha = new javax.swing.JLabel();
        LblHora = new javax.swing.JLabel();
        LblCorreo = new javax.swing.JLabel();
        TxtMotivo = new javax.swing.JTextField();
        BtnConfirm = new javax.swing.JButton();
        BtnCancelEdit = new javax.swing.JButton();
        CbBoxEspecialidad = new javax.swing.JComboBox<>();
        CbBoxDoctor = new javax.swing.JComboBox<>();
        CbBoxHora = new javax.swing.JComboBox<>();
        btnBuscarDoctores = new javax.swing.JButton();
        btnBuscarFecha = new javax.swing.JButton();
        btnBuscarHora = new javax.swing.JButton();
        DtChDia = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(106, 154, 176));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        BtnCitasSide.setBackground(new java.awt.Color(58, 109, 140));
        BtnCitasSide.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        BtnCitasSide.setForeground(new java.awt.Color(0, 0, 0));
        BtnCitasSide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/book_closed_icon_246534.png"))); // NOI18N
        BtnCitasSide.setText("Citas");
        BtnCitasSide.setBorder(null);
        BtnCitasSide.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BtnCitasSide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCitasSideMouseClicked(evt);
            }
        });
        BtnCitasSide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCitasSideActionPerformed(evt);
            }
        });

        BtnInfoSide.setBackground(new java.awt.Color(58, 109, 140));
        BtnInfoSide.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        BtnInfoSide.setForeground(new java.awt.Color(0, 0, 0));
        BtnInfoSide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/4092564-about-mobile-ui-profile-ui-user-website_114033.png"))); // NOI18N
        BtnInfoSide.setText("Información personal");
        BtnInfoSide.setBorder(null);
        BtnInfoSide.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BtnInfoSide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnInfoSideMouseClicked(evt);
            }
        });
        BtnInfoSide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInfoSideActionPerformed(evt);
            }
        });

        BtnHistorialSide.setBackground(new java.awt.Color(58, 109, 140));
        BtnHistorialSide.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        BtnHistorialSide.setForeground(new java.awt.Color(0, 0, 0));
        BtnHistorialSide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/calendar_date_day_event_month_schedule_time_icon_123230.png"))); // NOI18N
        BtnHistorialSide.setText("Historial");
        BtnHistorialSide.setBorder(null);
        BtnHistorialSide.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BtnHistorialSide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnHistorialSideMouseClicked(evt);
            }
        });
        BtnHistorialSide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHistorialSideActionPerformed(evt);
            }
        });

        BtnCitaEmSide.setBackground(new java.awt.Color(58, 109, 140));
        BtnCitaEmSide.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        BtnCitaEmSide.setForeground(new java.awt.Color(0, 0, 0));
        BtnCitaEmSide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/-weather-lightning_98198.png"))); // NOI18N
        BtnCitaEmSide.setText("Cita emergencia");
        BtnCitaEmSide.setBorder(null);
        BtnCitaEmSide.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BtnCitaEmSide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCitaEmSideMouseClicked(evt);
            }
        });
        BtnCitaEmSide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCitaEmSideActionPerformed(evt);
            }
        });

        BtnInicio.setBackground(new java.awt.Color(58, 109, 140));
        BtnInicio.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        BtnInicio.setForeground(new java.awt.Color(0, 0, 0));
        BtnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/3844470-home-house_110332.png"))); // NOI18N
        BtnInicio.setBorder(null);
        BtnInicio.setContentAreaFilled(false);
        BtnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BtnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnInicioMouseClicked(evt);
            }
        });
        BtnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnCitaEmSide, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnHistorialSide, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnInfoSide, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCitasSide, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnInicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(BtnInfoSide, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(BtnCitasSide, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(BtnHistorialSide, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(BtnCitaEmSide, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(BtnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BtnCancel.setBackground(new java.awt.Color(255, 255, 255));

        LblEspecialidad.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LblEspecialidad.setForeground(new java.awt.Color(0, 0, 0));
        LblEspecialidad.setText("Escpecialidad");

        LblDoctor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LblDoctor.setForeground(new java.awt.Color(0, 0, 0));
        LblDoctor.setText("Doctor");

        LblFecha.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LblFecha.setForeground(new java.awt.Color(0, 0, 0));
        LblFecha.setText("Seleccionar fecha");

        LblHora.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LblHora.setForeground(new java.awt.Color(0, 0, 0));
        LblHora.setText("Hora");

        LblCorreo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LblCorreo.setForeground(new java.awt.Color(0, 0, 0));
        LblCorreo.setText("Motivo de la cita");

        TxtMotivo.setBackground(new java.awt.Color(255, 255, 255));
        TxtMotivo.setEnabled(false);

        BtnConfirm.setBackground(new java.awt.Color(58, 109, 140));
        BtnConfirm.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BtnConfirm.setForeground(new java.awt.Color(0, 0, 0));
        BtnConfirm.setText("Confirmar");
        BtnConfirm.setBorder(null);
        BtnConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnConfirmMouseClicked(evt);
            }
        });

        BtnCancelEdit.setBackground(new java.awt.Color(58, 109, 140));
        BtnCancelEdit.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BtnCancelEdit.setForeground(new java.awt.Color(0, 0, 0));
        BtnCancelEdit.setText("Cancelar");
        BtnCancelEdit.setBorder(null);
        BtnCancelEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCancelEditMouseClicked(evt);
            }
        });
        BtnCancelEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelEditActionPerformed(evt);
            }
        });

        CbBoxEspecialidad.setBackground(new java.awt.Color(255, 255, 255));
        CbBoxEspecialidad.setMaximumRowCount(20);
        CbBoxEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CbBoxEspecialidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        CbBoxDoctor.setBackground(new java.awt.Color(255, 255, 255));
        CbBoxDoctor.setMaximumRowCount(20);
        CbBoxDoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CbBoxDoctor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        CbBoxHora.setBackground(new java.awt.Color(255, 255, 255));
        CbBoxHora.setMaximumRowCount(20);
        CbBoxHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CbBoxHora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        btnBuscarDoctores.setBackground(new java.awt.Color(58, 109, 140));
        btnBuscarDoctores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8-marca-de-verificación-20.png"))); // NOI18N
        btnBuscarDoctores.setBorder(null);
        btnBuscarDoctores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarDoctoresMouseClicked(evt);
            }
        });

        btnBuscarFecha.setBackground(new java.awt.Color(58, 109, 140));
        btnBuscarFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8-marca-de-verificación-20.png"))); // NOI18N
        btnBuscarFecha.setBorder(null);
        btnBuscarFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarFechaMouseClicked(evt);
            }
        });

        btnBuscarHora.setBackground(new java.awt.Color(58, 109, 140));
        btnBuscarHora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8-marca-de-verificación-20.png"))); // NOI18N
        btnBuscarHora.setBorder(null);
        btnBuscarHora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarHoraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BtnCancelLayout = new javax.swing.GroupLayout(BtnCancel);
        BtnCancel.setLayout(BtnCancelLayout);
        BtnCancelLayout.setHorizontalGroup(
            BtnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnCancelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(BtnCancelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(BtnCancelLayout.createSequentialGroup()
                .addGroup(BtnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BtnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BtnCancelLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(LblEspecialidad))
                        .addGroup(BtnCancelLayout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(LblDoctor))
                        .addGroup(BtnCancelLayout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(LblHora))
                        .addGroup(BtnCancelLayout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(BtnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CbBoxEspecialidad, 0, 294, Short.MAX_VALUE)
                                .addComponent(CbBoxDoctor, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CbBoxHora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DtChDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(BtnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnBuscarDoctores)
                                .addComponent(btnBuscarFecha)
                                .addComponent(btnBuscarHora)))
                        .addGroup(BtnCancelLayout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(LblFecha))
                        .addGroup(BtnCancelLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(LblCorreo))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        BtnCancelLayout.setVerticalGroup(
            BtnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnCancelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(LblEspecialidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BtnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarDoctores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CbBoxEspecialidad))
                .addGap(10, 10, 10)
                .addComponent(LblDoctor)
                .addGap(4, 4, 4)
                .addGroup(BtnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CbBoxDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BtnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarHora, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(DtChDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CbBoxHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BtnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCancelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(BtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnInfoSideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInfoSideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnInfoSideActionPerformed

    private void BtnCitasSideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCitasSideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCitasSideActionPerformed

    private void BtnHistorialSideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHistorialSideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnHistorialSideActionPerformed

    private void BtnCitaEmSideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCitaEmSideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCitaEmSideActionPerformed

    private void BtnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnInicioActionPerformed

    private void BtnCancelEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCancelEditActionPerformed

    private void BtnCancelEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCancelEditMouseClicked
        setVisible(false);
        FrmCitasPaciente frmCitas = new FrmCitasPaciente(identificador);
        frmCitas.setVisible(true);
    }//GEN-LAST:event_BtnCancelEditMouseClicked

    private void BtnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnInicioMouseClicked
        setVisible(false);
        FrmInicioPaciente frmInicio = new FrmInicioPaciente(identificador);
        frmInicio.setVisible(true);
    }//GEN-LAST:event_BtnInicioMouseClicked

    private void BtnInfoSideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnInfoSideMouseClicked
        FrmInfoPersPaciente frmInfoPerPac = new FrmInfoPersPaciente(identificador);
        frmInfoPerPac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnInfoSideMouseClicked

    private void BtnCitasSideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCitasSideMouseClicked
        FrmCitasPaciente frmCitas = new FrmCitasPaciente(identificador);
        frmCitas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnCitasSideMouseClicked

    private void BtnHistorialSideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHistorialSideMouseClicked
        FrmHistorialPaciente frmHistorial = new FrmHistorialPaciente(identificador);
        frmHistorial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnHistorialSideMouseClicked

    private void BtnCitaEmSideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCitaEmSideMouseClicked
        FrmCitaEmergencia frmCitaEm = new FrmCitaEmergencia(identificador);
        frmCitaEm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnCitaEmSideMouseClicked

    private void btnBuscarDoctoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarDoctoresMouseClicked
        try {
            String especialidad = (String) CbBoxEspecialidad.getSelectedItem();
            List<Doctor> doctores = citaBO.obtenerDoctoresPorEspecialidad(especialidad);
            DefaultComboBoxModel<String> doctoresModel = new DefaultComboBoxModel<>(doctores.stream().map(Doctor::getNombrePila).toArray(String[]::new));
            CbBoxDoctor.setModel(doctoresModel);
        } catch (NegocioException ex) {
            Logger.getLogger(FrmAgendarCitaPaciente.class.getName()).log(Level.SEVERE, "Error al cargar doctores por especialidad", ex);
            JOptionPane.showMessageDialog(this, "Error al cargar doctores por especialidad: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarDoctoresMouseClicked

    private void btnBuscarFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarFechaMouseClicked
    
    }//GEN-LAST:event_btnBuscarFechaMouseClicked

    private void BtnConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConfirmMouseClicked
        try {
            // Get the selected values from the combo boxes
            String especialidad = (String) CbBoxEspecialidad.getSelectedItem();
            Doctor doctor = (Doctor) CbBoxDoctor.getSelectedItem();
            Date fecha = (Date) DtChDia.getDate();
            String horaStr = (String) CbBoxHora.getSelectedItem();
            String motivo = TxtMotivo.getText();

            Time hora = Time.valueOf(horaStr + ":00");

            // Retrieve the patient's ID (assuming you have a method to get this)
            PacienteNuevoDTO paciente = pacienteBO.consultarPacientePorCorreo(identificador);

            
            
            CitaNuevoDTO nuevaCita = new CitaNuevoDTO("", fecha, hora, motivo, "Pendiente", doctor.getNombrePila(), especialidad);

            // Schedule the appointment
            citaBO.agendarCita(nuevaCita, identificador);

            // Show success message
            JOptionPane.showMessageDialog(this, "Cita agendada exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } catch (NegocioException ex) {
            Logger.getLogger(FrmAgendarCitaPaciente.class.getName()).log(Level.SEVERE, "Error al agendar la cita", ex);
            JOptionPane.showMessageDialog(this, "Error al agendar la cita: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnConfirmMouseClicked

    private void btnBuscarHoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarHoraMouseClicked
        try {
            Date fecha = (Date) DtChDia.getDate();
            List<Time> horarios = citaBO.obtenerHorasAtencion(identificador, fecha);

            // Convert Time to String
            SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");
            DefaultComboBoxModel<String> horariosModel = new DefaultComboBoxModel<>();
            for (Time hora : horarios) {
                horariosModel.addElement(timeFormat.format(hora));
            }
            CbBoxHora.setModel(horariosModel);
        } catch (NegocioException ex) {
            Logger.getLogger(FrmAgendarCitaPaciente.class.getName()).log(Level.SEVERE, "Error al cargar horarios de atención", ex);
            JOptionPane.showMessageDialog(this, "Error al cargar horarios de atención: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarHoraMouseClicked

    private void cargarEspecialidades() {
        try {
            List<String> especialidades = citaBO.obtenerEspecialidades();
            DefaultComboBoxModel<String> especialidadesModel = new DefaultComboBoxModel<>(especialidades.toArray(new String[0]));
            CbBoxEspecialidad.setModel(especialidadesModel);
        } catch (NegocioException ex) {
            Logger.getLogger(FrmAgendarCitaPaciente.class.getName()).log(Level.SEVERE, "Error al cargar especialidades", ex);
            JOptionPane.showMessageDialog(this, "Error al cargar especialidades: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAgendarCitaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAgendarCitaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAgendarCitaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAgendarCitaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnCancel;
    private javax.swing.JButton BtnCancelEdit;
    private javax.swing.JButton BtnCitaEmSide;
    private javax.swing.JButton BtnCitasSide;
    private javax.swing.JButton BtnConfirm;
    private javax.swing.JButton BtnHistorialSide;
    private javax.swing.JButton BtnInfoSide;
    private javax.swing.JButton BtnInicio;
    private javax.swing.JComboBox<String> CbBoxDoctor;
    private javax.swing.JComboBox<String> CbBoxEspecialidad;
    private javax.swing.JComboBox<String> CbBoxHora;
    private com.toedter.calendar.JDateChooser DtChDia;
    private javax.swing.JLabel LblCorreo;
    private javax.swing.JLabel LblDoctor;
    private javax.swing.JLabel LblEspecialidad;
    private javax.swing.JLabel LblFecha;
    private javax.swing.JLabel LblHora;
    private javax.swing.JTextField TxtMotivo;
    private javax.swing.JButton btnBuscarDoctores;
    private javax.swing.JButton btnBuscarFecha;
    private javax.swing.JButton btnBuscarHora;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
